// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcwjvrcwoikgxxfwugvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjd2p2cmN3b2lrZ3h4Znd1Z3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNTg0OTcsImV4cCI6MjA4MzYzNDQ5N30.2MuP9KnI1QBv7er82acc__lpNhSj7QjZFqZFkFL7WQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});