// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aradshpngiwszwblzpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyYWRzaHBuZ2l3c3p3Ymx6cGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMDg0NDUsImV4cCI6MjA4NTY4NDQ0NX0.6EBnAGoVUuDbtO9zRqf2NpmA7xHghB2QliKPzB5BuUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
